spring:
  datasource:
    url: "jdbc:h2:mem:community;MODE=PostgreSQL"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver

  # redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}

logging.level:
  org.hibernate:
    orm.jdbc.bind: trace
    SQL: debug

jwt:
  secret: "${JWT_SECRET}"


